### ISSUE TITLE
Lazy loading error on MoonShineUserResource

### ISSUE THREAD

**Issue by k-rustemuly** [CutCodeRu/moonshine-demo-project#10]
Attempted to lazy load [moonshineUserRole] on model [MoonShine\Permissions\Models\MoonshineUser] but lazy loading is disabled.
по ссылке http://127.0.0.1:8000/admin/resource/moon-shine-user-resource/index-page
добавил в MoonShineUserResource:
```
    protected array $with = ['moonshineUserRole'];
```
ошибка исчезла

**Comment by lee-to** [comment]
Сделаешь пр?

**Comment by k-rustemuly** [comment]
> Сделаешь пр?

ok
