### ISSUE TITLE
Ошибка Route [profile.store] not defined

### ISSUE THREAD

**Issue by shevl-dev** [CutCodeRu/moonshine-demo-project#20]
При выключенном режиме **DEMO_MODE** на странице профиля выбрасывается исключение **"Route [profile.store] not defined"**.
Как я понимаю это сделано, чтобы в публичной версии демо проекта нельзя было редактировать профиль, но может как-то по другому это обыграть, чтобы в локальном копии проекта не получать эту ошибку?

**Comment by lee-to** [comment]
По идеи при demo_mode = false этот роут должен быть, ты уверен что кеш роутов был сброшет после изменения конфига?

**Comment by shevl-dev** [comment]
> По идеи при demo_mode = false этот роут должен быть, ты уверен что кеш роутов был сброшет после изменения конфига?

При разворачивании проекта конфиг по умолчанию false, я его не менял, а кеш роутов отключён.
Я могу ошибаться, но ощущение, что форма рендерится раньше, чем подключаются стандартные роуты муншайна из файла 
**/routes/moonshine.php**

**Comment by lee-to** [comment]
Пофиксил, не хватало префикса у стандартного режима
