### ISSUE TITLE
showOnExport() и useOnImport() у полей ресурсов

### ISSUE THREAD

**Issue by shevl-dev** [CutCodeRu/moonshine-demo-project#22]
Заметил, что у многих ресурсов в проекте у полей не указаны **showOnExport()** и **useOnImport()**, поэтому скачивается пустой файл.

Вопрос, что лучше сделать:
- отключить импорт\экспорт по умолчанию через конфиг, и инициировать этот функционал у какой-то одной модели для примера?
- наоборот, во всех ресурсах, где сейчас включён импорт\экспорт, добавить всем полям **showOnExport()** и **useOnImport()**?

**Comment by lee-to** [comment]
Да я тоже заметил эту не приятную особенность, мне кажется стоит выбрать один ресурс для демонстрации и в нем включить пару полей а в остальных отключить

**Comment by shevl-dev** [comment]
> Да я тоже заметил эту не приятную особенность, мне кажется стоит выбрать один ресурс для демонстрации и в нем включить пару полей а в остальных отключить

Хорошо, сделаю 👍
